name: roadsurferdemo
description: "roadsurfer demo project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  map: ^2.0.2
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  intl: ^0.20.2
  flutter_localization: ^0.3.2
  equatable: ^2.0.7
  # json class builder
  json_annotation: ^4.9.0
  flutter_map: ^8.1.1
  flutter_map_cancellable_tile_provider: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^3.0.6
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: EncodeSans
      fonts:
        - asset: fonts/EncodeSans-Thin.ttf
          weight: 100
        - asset: fonts/EncodeSans-Light.ttf
          weight: 300
        - asset: fonts/EncodeSans-Regular.ttf
          weight: 400
        - asset: fonts/EncodeSans-Medium.ttf
          weight: 500
        - asset: fonts/EncodeSans-Bold.ttf
          weight: 700
        - asset: fonts/EncodeSans-Black.ttf
          weight: 900
