// Mocks generated by Mockito 5.4.6 from annotations
// in roadsurferdemo/test/features/campsites/data/repositories/campsite_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:roadsurferdemo/features/campsites/data/data_sources/campsite_remote_data_source.dart'
    as _i2;
import 'package:roadsurferdemo/features/campsites/data/data_sources/geocoding_remote_data_source.dart'
    as _i5;
import 'package:roadsurferdemo/features/campsites/data/models/campsite_model.dart'
    as _i4;
import 'package:roadsurferdemo/features/campsites/data/models/geocoding_model.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CampsiteRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCampsiteRemoteDataSource extends _i1.Mock
    implements _i2.CampsiteRemoteDataSource {
  @override
  _i3.Future<List<_i4.CampsiteModel>> fetchCampsites() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCampsites, []),
            returnValue: _i3.Future<List<_i4.CampsiteModel>>.value(
              <_i4.CampsiteModel>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.CampsiteModel>>.value(
                  <_i4.CampsiteModel>[],
                ),
          )
          as _i3.Future<List<_i4.CampsiteModel>>);
}

/// A class which mocks [GeocodingRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeocodingRemoteDataSource extends _i1.Mock
    implements _i5.GeocodingRemoteDataSource {
  @override
  _i3.Future<_i6.GeoCodingModel?> getLocationComponents({
    required double? lat,
    required double? long,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLocationComponents, [], {
              #lat: lat,
              #long: long,
            }),
            returnValue: _i3.Future<_i6.GeoCodingModel?>.value(),
            returnValueForMissingStub: _i3.Future<_i6.GeoCodingModel?>.value(),
          )
          as _i3.Future<_i6.GeoCodingModel?>);
}
